name: CI Cache
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: prime-cache-899883c
      id: cache-step
      uses: actions/cache@v4
      with:
        key: cache-899883c
        path: ~/.npm
    - name: Echo result
      run: echo "Cache: ${{ steps.cache-step.outputs.cache-hit }}"
