name: CI Cache
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: prime-cache-899883c
      id: prime-cache-899883c
      uses: actions/cache@v4
      with:
        key: cache-899883c
        path: ~/.npm
    
    - name: Echo cache result
      run: echo "Cache hit/miss: ${{ steps.prime-cache-899883c.outputs.cache-hit }}"
